spring:
  application:
    name: "library-is"

  profiles:
    default: local

  config:
    import:
      - optional:file:.env[.properties]
      - classpath:application-db.yml

server:
  address: 0.0.0.0
