#Data Source Properties
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost:5432/library-is-db}
    username: ${DB_USERNAME:library}
    password: ${DB_PASSWORD:library}
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000

  #JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: validate
